version: 0.2
cache:
  paths:
  - ~/.cache/pip/**/*
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install boto3 cfn-flip
  pre_build:
    commands:
    - echo "Building with $(python --version)"
  build:
    commands:
    - mkdir -p build
    - ./scripts/package.sh "$ARTIFACTS_BUCKET_NAME" "$ARTIFACTS_BUCKET_CFN_ASSET_PREFIX"
  post_build:
    commands:
    - echo Build completed on $(date)
artifacts:
  files:
  - build/*

 