Description: Development Account

Parameters:
  AccountName:
    Type: String
  AccountEmail:
    Type: String
  OrgRegions:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Default: /org/regions
  
Resources:
  DummyParamter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /account/${AccountName}
      Value: !Ref AccountEmail
      Type: String

Outputs:
  AccountName:
    Value: !Ref AccountName